config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'

  resources :topics, only: [:index, :show ]
  resources :events, only: [:index, :show ]

  resources :articles, only: [:index, :show ] do
    resources :user_scores, only: [:create ]
    resources :save_articles, only: [:create, :destroy]
  end

  resources :profile, only: [:edit, :update, :show ]
  resources :following_items, only: [:create, :destroy]

  # resources :map, only: [:index ]
  get '/map', to: 'maps#map'

end

app/models/topic.rb
class Topic < ApplicationRecord

  validates :name, presence: true
  has_many :events, dependent: :destroy

  def self.adjacent(collection, current_id, direction)
    # Taking an array of id's, from collection(articles)
    ids = collection.pluck(:id)
    # Taking the current article id and finding its index
    current_index = ids.index(current_id)
    # taking that index and its direction either -1 or +1, whilest checking not to excede the array. giving back an index
    adjacent_index = (current_index.send(direction, 1)) % ids.length
    # returning the id of the an ajacent aricle from the index passed
    adjacent_id = ids[adjacent_index]
    # then fining the instance in the database
    self.find(adjacent_id)
  end

  include PgSearch
  multisearchable :against => [:name]
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]

  def index
    if params[:query].present?
      @documents = PgSearch.multisearch(params[:query]).limit(10)
      @articles = Article.all
      @topics = Topic.all
    else
      @documents = []
      @articles = Article.all
      @topics = Topic.all
    end
  end

  def show
      @articles = Article.all

      @topic = Topic.find(params[:id])
      @events = @topic.events
  end

end

app/views/topics/index.html.erb
<!-- [ TOPICS INDEX ]  ------------------------------------- -->

<!-- [ PAGE HEADER ]  ---------------- START --------------- -->

<div class="header">

    <div class="banner-half"

     style="background-image:
        linear-gradient(-225deg,
        rgba(18,240,181,0.6) 0%,
        rgba(15,153,200,0.8) 50%),
        url(<%= @topics.all.sample.image_url %>);">

        <!-- [ PAGE HEADER ][ COL-1 - LEFT ] ----------- START --------------- -->
        <!-- [           LEFT            ] -->

          <div class="flex-header-1">
          <div>
          <!-- LEFT END -->

        <!-- [           LEFT            ] -->
       <!-- [ PAGE HEADER ][ COL-1 - LEFT ] -------------- END --------------- -->

      <!-- ------------------------------------------------------------------- -->

       <!-- [ PAGE HEADER ][ COL-2 - MIDDLE ] ----------- START -------------- -->
        <!-- [        TITLES           ] -->

          <div class="flex-header-2 text-center">

              <!-- TOPIC HEADER -->
              <h2><span
                class="blocked">&nbsp News Topics &nbsp
              </span></h2>
              <!-- EVENT HEADER -->
              <p></p>
              <p></p>
              <p>The collection of all the news topics in sift</p>

          </div>
            <!-- TITLE END -->

          </div>
          <!-- BANNER HALF -->
      </div>
      <!-- HEADER -->

        <!-- [        TITLES           ] -->
       <!-- [ PAGE HEADER ][ COL-2 - MIDDLE ] ----------- END --------------- -->


            <!-- NEW SEARCH ------------------------------- -->
            <!--
            <div class="form-group">

              <div class="input-group">

                <input value=""
                      placeholder="Topics, Events, Locations" class="form-control input-search"
                      id="query"
                      pattern=".*\w{3,}.*"
                      title="Words expected"
                      type="text"
                      name="keyword">
                <span class="input-group-btn"><button name="button" type="submit" class="btn btn-search"><i class="fas fa-arrow-right"></i></button></span>

              </div>
              -->
              <!-- input group end -->
            <!-- </div> -->
            <!-- form group end -->
            <!-- NEW SEARCH END------------------------------- -->

            <!-- SEARCH --------------------------------------- -->
<!--             <div class="form-group">

                <#%= text_field_tag :query, nil, placeholder: 'search',
                  class: 'form-control'
                %>

               <#%= link_to "", topics_path,
                class: "fas fa-arrow-right btn btn-green" %>

                <#%= submit_tag "Search",
                  class: "fas fa-arrow-right btn btn-default"
                %>

            </div> -->
            <!-- SEARCH END--------------------------------------- -->



            <!-- ---- HEADER CARD END ----- -->

</div>
<!-- [ PAGE HEADER ]  ---------------- END ----------------------------- -->

<!-- ------------------------------------------------------------------- -->

<!-- [ PAGE BODY ]  ----------------- START ---------------------------- -->

<div class="container">
<div class="row">

  <!-- [ PAGE BODY ][ COL-1 - LEFT ] ----------- START --------------- -->
  <!-- [           LEFT            ] -->

  <div id="col-1-left" class="
    col-xs-0
    col-xs-offset-0
    col-sm-0
    col-xs-offset-0
    col-md-0
    col-md-offset-0
    col-lg-0
    col-lg-offset-0">
    <!-- STUFF HERE-->
  <div>

  <!-- [ PAGE BODY ][ COL-2 - MIDDLE ] ----------- START --------------- -->
  <!-- [        CONTENT           ] -->
  <!-- [       QUERY LIST         ] ---------------------------------- -->

  <div id="col-2-content" class="
    col-xs-12
    col-xs-offset-0
    col-sm-12
    col-xs-offset-0
    col-md-12
    col-md-offset-0
    col-lg-12
    col-lg-offset-0">

      <p>All Topics within sift:</p>
      <%  @topics.each_with_index do | topic, i | %>

      <br>

      <!-- ---- [ TOPIC CARD ]  ----------------------------------- START ------------------------ -->

        <div class="a-card-event-box"
        style="background-image:
          linear-gradient(-225deg,
          rgba(18,240,181,0.6) 0%,
          rgba(15,153,200,0.8) 50%),
          url(<%= topic.image_url %>);">
        <h3>#<%= (i + 1) %></h3>
          <p></p>
          <p></p>
          <p></p>
          <p></p>
            <span class="blocked-sml">&nbsp &nbsp <%#= topic.events.first.location %>  &nbsp &nbsp</span>
            <span class="blocked-sml">&nbsp &nbsp <%#= topic.events.first.date_time %>  &nbsp &nbsp</span>
          <p></p>
            <h2><span class="blocked">&nbsp # &nbsp</span> <span class="blocked">&nbsp <%= topic.name %> &nbsp</span></h2>
          <p></p>
            <h2><span class="blocked">&nbsp # &nbsp</span> <span class="blocked">&nbsp <%= topic.events.count %> events &nbsp</span></h2>
          <p></p>
          <p></p>
          <p>Summary: { <%= topic.events.count %> }, between { 3rd Jan 2018 } and { 24th Dec 2018 } The story of: ...</p>
          <%= link_to 'See topic', topic_path(topic), class:"btn btn-outline-grey"%>
        </div>

      <!-- ---- [ TOPIC CARD ] ----------------------------------- END ------------------------ -->

      <% end %>

    </div>
    <!-- [ PAGE BODY ][ COL-2 - MIDDLE ] ----------- END --------------- -->
  </div>
  <!-- [ ROW ][ END ] -->
</div>
<!-- [ CONTAINER ][ END ] -->

<!-- [ PAGE BODY ]  ----------------- END -------------- -->

app/views/topics/show.html.erb
<!-- [ TOPICS INDEX ]  ------------------------------------- -->

<!-- [ PAGE HEADER ]  ---------------- START --------------- -->


<div class="header">

    <div class="banner-half"

     style="background-image:
        linear-gradient(-225deg,
        rgba(18,240,181,0.6) 0%,
        rgba(15,153,200,0.8) 50%),
        url(<%= @topic.image_url %>);">

        <!-- [ PAGE HEADER ][ COL-1 - LEFT ] ----------- START --------------- -->
        <!-- [           LEFT            ] -->

          <div class="flex-header-1">
          <div>
          <!-- LEFT END -->

        <!-- [           LEFT            ] -->
       <!-- [ PAGE HEADER ][ COL-1 - LEFT ] -------------- END --------------- -->

      <!-- ------------------------------------------------------------------- -->

       <!-- [ PAGE HEADER ][ COL-2 - MIDDLE ] ----------- START -------------- -->
        <!-- [        TITLES           ] -->

          <div class="flex-header-2 text-center">

            <!-- ---- [ HEADER TITLES CARD ] ------ START --------- -->

              <!-- LOCATION TAG -->
              <p><span class="blocked-tag">&nbsp <%= @topic.events.first.location %>  &nbsp</span></p>
              <!-- TIME TAG -->
              <p><span class="blocked-tag">&nbsp <%= @topic.events.first.articles.first.date_time_published %>  &nbsp</span></p>
              <p></p>

              <h2>
                <%= link_to(@topic) do %>
                  <span class="blocked topic-title">
                    &nbsp <%= @topic.name %> &nbsp
                  </span>
                <% end %>
              </h2>
              <p>Description:<%= @topic.events.first.description %></p>
                           <p> With <%= @topic.events.count %> Events</p>

            <!-- ---- [ HEADER TITLES CARD ] ------ END --------- -->

          </div>
            <!-- TITLE END -->

        <!-- [        TITLES           ] -->
       <!-- [ PAGE HEADER ][ COL-2 - MIDDLE ] ----------- END --------- -->

          </div>
          <!-- BANNER HALF -->
      </div>
      <!-- HEADER -->

</div>
<!-- [ PAGE HEADER ]  ---------------- END ----------------------------- -->


<!-- ------------------------------------------------------------------- -->
<!-- [ PAGE BODY ]  ---------------- START ----------------------------- -->

<!-- [ TOPICS EVENTS LIST ]  ------------------------------- -->

<div class="container">
  <div class="row">
    <div class='offset-xs-0 col-xs-12 offset-md-0 col-md-12'>


              <p>All news events of from <%= @topic.name %> :</p>
              <%  @events.each_with_index do | event, i | %>

              <br>
                <!-- ---- EVENT CARD ----- -->

                <div class="a-card-event-box"
                style="background-image:
                  linear-gradient(-225deg,
                  rgba(150,10,115,0.8) 0%,
                  rgba(255,77,0,0.4) 50%),
                url(<%= event.image_url %>);">
                <h3>#<%= (i + 1) %></h3>
                  <p></p>
                  <p></p>
                  <p></p>
                  <p></p>
                    <span class="blocked-sml">&nbsp &nbsp <%#= event.events.first.location %>  &nbsp &nbsp</span>
                    <span class="blocked-sml">&nbsp &nbsp <%#= event.events.first.date_time %>  &nbsp &nbsp</span>
                  <p></p>
                    <h2><span class="blocked">&nbsp # &nbsp</span>
                      <%= link_to(event.topic) do %>
                        <span class="blocked">&nbsp <%= event.topic.name %> &nbsp</span>
                      <% end %>
                    </h2>
                  <p></p>
                    <h2><span class="blocked">&nbsp # &nbsp</span>
                      <%= link_to(event) do %>
                        <span class="blocked">
                          &nbsp <%= event.name %> &nbsp
                        </span>
                      <% end %>
                    </h2>

                  <p></p>
                  <p></p>
                  <p>Summary: { <%= event.articles.count %> articles }, between { 3rd Jan 2018 } and { 24th Dec 2018 } The story of: <%= event.description %></p>
                  <%= link_to 'See Event', event_path(event), class:"btn btn-outline-grey"%>
                </div>

                <!-- ---- EVENT CARD END ----- -->

              <% end %>

    </div> <!-- col end -->
  </div> <!-- row end -->
</div> <!-- container end -->