config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'

  resources :topics, only: [:index, :show ]
  resources :events, only: [:index, :show ]

  resources :articles, only: [:index, :show ] do
    resources :user_scores, only: [:create ]
    resources :save_articles, only: [:create, :destroy]
  end

  resources :profile, only: [:edit, :update, :show ]
  resources :following_items, only: [:create, :destroy]

  # resources :map, only: [:index ]
  get '/map', to: 'maps#map'

end

app/views/shared/_card_article.html.erb
    <!-- ---- [ ARTICLE CARD ]  ----- -->

    <%= link_to article_path(article), class: 's-card-article' do %>

        <div class="s-image-article"
          style="background-image:
          linear-gradient(-225deg,
          rgba(161,90,187,0.8) 0%,
          rgba(45,23,54,0.2) 50%),
          url(<%= article.image_url %>);">

        <div class="event-header">

          <div class="event-index">
            <h3>#<%= (i + 1) %></h3>
          </div>

          <div class="event-num-articles text-right">
             <h4><%= (article.body_text.reading_time :format => :approx).include?('seconds') ===false ? (article.body_text.reading_time :format => :approx) : '1 minute' %></h4>
          </div>

        </div>

        </div>

        <div class="s-card-publisher">
            <h3 class="s-card-header-text"><%= article.publisher.name %></h3>
            <img class="s-image-publisher" src= <%= article.publisher.image_url %> >
        </div>

        <div class="s-card-body s-card-text" >
          <h3 class="article-title"><%= article.title %></h3>
          <h5 class="article-description"><%= article.description%></h5>

            <% day_num = article.date_time_published.strftime("%l").to_i %>
                <% case day_num
                   when 1 %><% date_sufix = 'st' %>
                <% when 2 %><% date_sufix = 'nd' %>
                <% when 3 %><% date_sufix = 'rd' %>
                <% else %><% date_sufix = 'th' %>
                <% end %>

          <div class="article-card-footer">

              <div class="article-date txt-outline-grey">
                <i class="far fa-calendar"></i>
                 <%= article.date_time_published.strftime("%e")%><%= date_sufix %>
              </div>

              <div class="article-hour text-center txt-outline-grey">
                <i class="far fa-clock"></i>
                <%= article.date_time_published.strftime("%l")%>.00
              </div>

          </div>

      </div>

      <% end %>

    <!-- ---- [ ARTICLE CARD ]  ----- -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <p class="navbar-wagon-link">Sift</p>
    <!-- <#%= image_tag "logo.png", height: 50 %> -->
  <% end %>

  <div>
    <%= link_to "Home", root_path,
    class: "navbar-wagon-item txt-link" %>
    <%= link_to "Topics", topics_path,
    class: "navbar-wagon-item txt-link" %>
    <%= link_to "Events", events_path,
    class: "navbar-wagon-item txt-link" %>
    <%= link_to "Map", map_path,
    class: "navbar-wagon-item txt-link" %>
  </div>



  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <% if current_user.photo.nil? %>

          <% else %>
            <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>

              <% if user_signed_in? %>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                 <li role="separator" class="divider"></li>

                <li><%= link_to 'Profile', profile_path(current_user) %></li>
                <li><%= link_to 'Edit Profile', edit_profile_path(current_user) %></li>
                 <li role="separator" class="divider"></li>

                <li><%= link_to "Articles", articles_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Topics", topics_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Events", events_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to "Map", map_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

              <% else %>
                <li><%= link_to 'Log In', new_user_session_path %></li>
                <li role="separator" class="divider"></li>

                <li><%= link_to "Features", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "About us", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
                 <li role="separator" class="divider"></li>

                <li><%= link_to "Latest Articles", articles_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Topics", topics_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Current Events", events_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to "Map", map_path, class: "navbar-wagon-item navbar-wagon-link" %></li>


              <% end %>

<!--               <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li> -->

          </ul>

        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
              <% if user_signed_in? %>
                <li><%= link_to 'Profile', profile_path(current_user) %></li>
                <li><%= link_to 'Edit Profile', edit_profile_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>

              <% else %>
                <li><%= link_to 'Log In', new_user_session_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Latest Articles", articles_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Topics", topics_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Current Events", events_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Features", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "About us", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <% end %>
        </li>
      </ul>
    </div>
  </div>


</div> <!-- end - fixed header div (starts in nav) -->